name       : perl-devel-stacktrace
version    : '2.03'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Devel-StackTrace-2.03.tar.gz : 7618cd4ebe24e254c17085f4b418784ab503cb4cb3baf8f48a7be894e59ba848
license    : Artistic-2.0
component  : programming.perl
summary    : An object representing a stack trace
description: |
    The Devel-StackTrace module contains two classes, C,Devel-StackTrace> and Devel-StackTrace-Frame. These objects encapsulate the information that can retrieved via Perl's caller() function, as well as providing a simple interface to this data.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
