name       : perl-devel-stacktrace
version    : '2.02'
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Devel-StackTrace-2.02.tar.gz : cbbd96db0ecf194ed140198090eaea0e327d9a378a4aa15f9a34b3138a91931f
license    : Artistic-2.0
component  : programming.perl
summary    : An object representing a stack trace
description: |
    The Devel-StackTrace module contains two classes, C,Devel-StackTrace> and Devel-StackTrace-Frame. These objects encapsulate the information that can retrieved via Perl's caller() function, as well as providing a simple interface to this data.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
