name       : perl-devel-stackTrace
version    : 2.00
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Devel-StackTrace-2.00.tar.gz : 1debe7273099a60e1386e0da5edbed7334db3cf3ed8e3b4106b087100b8ec5e4
license    : Artistic-2.0
summary    : Perl Devel Stacktrace Module
description: |
    The Devel-StackTrace module contains two classes, C,Devel-StackTrace> and Devel-StackTrace-Frame. These objects encapsulate the information that can retrieved via Perl's caller() function, as well as providing a simple interface to this data.
builddeps  :
setup      : |
    perl Makefile.PL PREFIX=/usr INSTALLDIRS=vendor DESTDIR=%installroot%
build      : |
    %make
install    : |
    %make_install
